services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb 

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana 

  k6_runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    command: ["./run_full_test.sh"]
    volumes:
      - .:/app # Mounts local project directory into the container
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BASE_URL=${BASE_URL}
      - USER_PASSWORD=${USER_PASSWORD}
      - K6_OUT=influxdb=http://influxdb:8086/k6

volumes: 
  influxdb-data: 
  grafana-data:  