version: '3.9'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana

  k6_runner:
    image: grafana/k6:latest
    depends_on:
      - influxdb
    command: ["run", "--out", "influxdb=http://influxdb:8086/k6", "--out", "json=k6_results.json", "test.js"]
    environment:
      - BASE_URL=${BASE_URL}
    volumes:
      - .:/app
    working_dir: /app

volumes:
  influxdb-data:
  grafana-data:
